### ISSUE TITLE
How to add multiple channels?

### ISSUE THREAD

**Issue by nckwdfrm** [Hansen8601/control4-mediaplayer#2]
Hello! Thanks for this integration, I am pumped to get it up and running fully!  

I am having trouble figuring out getting each channel of this amp into HA. No matter how I set it up, it only ever shows the last named zone

I have tried a few ways of formatting my yaml, the most recent of which is below. How should the yaml look? Thanks for your time!

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
zeroconf:

        
media_player:
    platform: control4-mediaplayer
    name: MBR
    host: 192.168.1.217
    channel: 1
    name: MBath
    host: 192.168.1.217
    channel: 2
    name: Audio for Boys Room!
    host: 192.168.1.217
    channel: 3
    name: Output4
    host: 192.168.1.217
    channel: 4
    name: Rears
    host: 192.168.1.217
    channel: 7
    source_list:
      - EA3
      - In2
      - Yamaha Zone 2
      - In4
        In5
      - In6
      - In7
      - In8

**Comment by Hansen8601** [comment]
Each channel has its own HA media player. Below is how your first two should look, and follow that format for the next.



```
media_player:
  - platform: control4-mediaplayer
    name: MBR
    host: 192.168.1.217
    channel: 1
    source_list:
      - EA3
      - In2
      - Yamaha Zone 2
      - In4
      - In5
      - In6
      - In7
      - In8
  - platform: control4-mediaplayer
    name: MBath
    host: 192.168.1.217
    channel: 2
    source_list:
      - EA3
      - In2
      - Yamaha Zone 2
      - In4
      - In5
      - In6
      - In7
      - In8
```
